version: '3.8'

services:
  feedback-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/feedback.db
    restart: unless-stopped